### ISSUE TITLE
feature idea: Have an "auto-pip" option

### ISSUE THREAD

**Issue by sh0rtcircuit** [usnistgov/pyproject2conda#8]
### Description

The default pyproject.toml package source is pypi (not conda). I think many people use a conda environment purely with pip dependencies, i.e. the conda.yml looks something like this:

```yaml
name: myenv
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - matplotlib
    - notebook
    - pandas
    - plotly
```

Currently, I would have to manually do `athing = { pip = true }` for every dependency individually to make it show up as a "pip" package in the conda.yml. Maybe an option something like
`pyproject2conda yaml -f ./pyproject.toml --all-pip` could help. Just as an idea ✌️😃
